server:
  port: 5001

spring:
  application:
    name: USER-SERVICE
  jpa:
    hibernate:
      ddl-auto: update
    # show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/task_user_service
    username: springstudent
    password: springstudent
    driver-class-name: com.mysql.cj.jdbc.Driver
  main:
    banner-mode: off

logging:
  pattern:
    console: "%d{yyyy-MMM-dd HH:mm:ss.SSS} [%thread] %highlight(%-5level) %cyan(%logger{15}) - %msg %n"

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

